---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: gitlab-auth
  namespace: apps
spec:
  encryptedData:
    password: AgBIBxHfRyvHhP1+AA/rDjzcvd57LkSA8M1slFVNZ9ko3MtAXvqD7UcyS6lGw0+saqYXldgoADyV7Ll/SEwhXiyVgps7Ji5PD12+uwE5Eo3vGECsO6WLix5hUkPyhR7ZYPTNXIRJGe0AFBFdJhEi7IgATiwwf4fXAhpVh4X4ZaTwx0G+r+Lj7H6PcHrG2+5mozrqnwnCBz6NAWihnVEZ1QmLDwwKMPHYml1efnXzlwd7ZudMvtPbDtHOjfZnyEkayi3SG9FrM63ioBWj872VNOKG2qm/EoGQRz+detp9mhfZKXDDt7Y5a8gWPUnhKt7uK4R42ue8F2qJgESsif/wKDeW4NKGOMd71XJyFN8YWSvOEVjgvVH4SsAZeuZpXWA3aObgUXnxz3b4yyKAgFCXAH6xAl7RrQvg68JltNoCcSCFSGjImvO0pkkLqx2/aQwXBpV+K54NXh2fMnQebHCSJz3eGicmTl5+neZdtVC2b3jvC9/sNILxlu6d0YO5bK8eLEeuKYx89snE5iEV99OdlRcGaiNZlxmi3x77l8sNVYo4S4kcKAOE488as7Niu7NCX4Ww2pseZo+WwXnO0egwTfF5/40b+LKV54eV9AW/6Zzg2iV9ChkVVTXy8r6oB/nZxsNNxrEhNZchXWUnwKdJgleNv9j4iPpqdM40/xondHhVVr0RJiNZN69xX1KTysYlMdZaVlhJ5QNDxp7svqvBIVu3bT3gRp/B4jrc6w==
    username: AgCJxYLssSTmbutxGD+xlAMG4ts0ISSrkeVIJyC+MOrVJ2KxWcWMr3Iy0CMvMeerIGNjO57WCZukwoNz6rKNUuD7HG5DDKg/ZpFzUKEcCsUPw8UrReXhGJ5OdujePbzGd9AsBWcU8R57yBLzG1YlVB8WrEARzKN+f7RtsXInLk0aXTkw/TY7NXc8EIlo/+VJb2dyt0cidTjrqpkHawn7/E71kuuYantgSUsvVss1Pt/DksUMKXHv3sFutHWVhcMEuX9DNqBJIA8vvfPIcNahk+ES3Cto7SUrdViViQngWjMPm3nqqu0YQkX6M9OAao7VZGrkKgFPFKr+DDitYtJIL03mbhAshdGVn4FhnDJhom5aHbutUi5ba8aYPGirEn6meEom1Vg2YOFGHUL9S6D4RxRU+45LeAu4xJi23D34VLbun3ZlwJXNUX0ZaJejJBShx5GJumqWZwqN7CQ1Gghaq6OGD7DbVUTCoSMNLByw+rt8wyVNbOkSjNFLHNX5Pr2gFb48GRO0zlbHXDHCSRCA11hjY/V+pVDNrDQGjvmadCC/UWcqFifX2IjGk/gr6Ac5eSwqZKpWuqa6fuR6m8DCbbn6ZyKwqwsX0vVC5KexGo9SFMydN0jmxJ3VFkHHEH2H4cs1RnHvpxjQ+/evmZU8R0iFYS1fY2P4gz+l074b/I5WJ+8cITtoRSbnmxR2Y8xejiqSVZ1GFfQYIZGrZOHGGEhdmtw=
  template:
    metadata:
      name: gitlab-auth
      namespace: apps
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: dev
  namespace: apps
spec:
  interval: 1m0s
  ref:
    branch: main
  secretRef:
    name: gitlab-auth
  url: https://gitlab.com/abohmeed/myweatherapp
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: gitlab
  namespace: apps
spec:
  interval: 1m0s
  secretRef:
    name: gitlab-auth
  type: oci
  url: oci://registry.gitlab.com/abohmeed/myweatherapp
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: dev
  namespace: apps
spec:
  interval: 1m0s
  path: ./
  prune: false
  serviceAccountName: dev
  sourceRef:
    kind: GitRepository
    name: dev
